# Generated by Django 4.2.4 on 2023-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_tg',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='логин телеграмм'),
        ),
    ]
